#!/usr/bin/env node
import { readdirSync, readFileSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { basename, join, relative, resolve, sep } from 'node:path';

const VERSION = '1.3.0';
const OKF_VERSION = '0.2';

const USAGE = `usage:
  okf.mjs index <bundle-root> [--stdout] [--describe <dir>=<text>]...
  okf.mjs check <bundle-root>
  okf.mjs wire  <bundle-root> [--stdout]
  okf.mjs --version

<bundle-root>/.okfignore, if present, lists paths this skill does not own: one
bundle-root-relative path per line, trailing / for a directory, # for a comment.
They are not enumerated, not checked, and never stamped.

exit: 0 ok | 1 violations | 3 profiled repo, out of scope | 77 nothing evaluated | 64 usage`;

const RESERVED = new Set(['index.md', 'log.md']);
const PROJECT_META = new Set([
  'readme.md', 'license.md', 'licence.md', 'contributing.md', 'code_of_conduct.md',
  'security.md', 'changelog.md', 'claude.md', 'agents.md', 'gemini.md',
  'third-party-notices.md', 'notice.md', 'authors.md', 'maintainers.md',
]);
const SKIP_DIRS = new Set(['node_modules', '__pycache__']);
const IGNORE_FILE = '.okfignore';

const GEN_MARKER = '<!-- generated by okf.mjs - do not edit; regenerate after changing frontmatter -->';
const SUBDIR_HEADING = 'Subdirectories';
const UNTYPED_HEADING = 'Other';
const ENTRY_RE = /^\* \[([^\]]*)\]\(([^)]*)\)(?: - (.*))?$/;
const KEY_RE = /^([A-Za-z0-9_.-]+):(?:[ \t]+(.*))?$/;
const PROFILE_RE = /^profile:[ \t]*(\S.*?)[ \t]*$/;
const NESTED_RE = /^[ \t]+(?:- )?(?:[A-Za-z0-9_.-]+:(?:[ \t].*)?|- .*|\{.*\}|.+)$/;
const BLOCK_RE = /^([|>])[1-9]?[+-]?$/;

const DESC_MAX = 160;
const oneLine = (value) => String(value ?? '').replace(/\s+/g, ' ').trim();

function gated(raw, label, reports) {
  const text = oneLine(raw);
  if (text.length <= DESC_MAX) return text;
  reports.push(`${label} (${text.length} chars, max ${DESC_MAX})`);
  return '';
}

const ENTRY_OPEN = '<!-- okf:entry -->';
const ENTRY_CLOSE = '<!-- /okf:entry -->';
const ENTRY_BLOCK_RE = /<!-- okf:entry -->[\s\S]*?<!-- \/okf:entry -->/;
const ENTRY_BLOCK = `${ENTRY_OPEN}
## Documentation

Start at [index.md](index.md). Every documentation folder carries a generated \`index.md\` listing
each document's title and one-line description — answer "which doc covers X" and "does a doc for Y
exist" from that index in one read, and open a document only after the index names it. Do not grep
\`docs/\` for a document's identity; grep stays correct only for a literal phrase inside a body that
the index cannot carry.
${ENTRY_CLOSE}`;
const PROSE_ENTRY_FILES = ['CLAUDE.md', 'AGENTS.md'];
const IMPORT_ENTRY_FILE = 'GEMINI.md';
const IMPORT_LINE = '@index.md';

const byCodepoint = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

const relPath = (root, path) => relative(root, path).split(sep).join('/');

function readIgnores(root) {
  const state = { entries: [], skipped: [], present: false };
  let text;
  try { text = readFileSync(join(root, IGNORE_FILE), 'utf8'); } catch { return state; }
  state.present = true;
  text.split('\n').forEach((raw, i) => {
    const line = raw.replace(/\r$/, '').trim();
    if (!line || line.startsWith('#')) return;
    const isDir = line.endsWith('/');
    const target = (isDir ? line.slice(0, -1) : line).replace(/^\.\//, '').replace(/\/+$/, '');
    if (!target) return;
    state.entries.push({ target, isDir, lineno: i + 1, hits: 0 });
  });
  return state;
}

function ignoreHit(state, rel, isDir) {
  for (const entry of state.entries) {
    if (entry.isDir !== isDir || entry.target !== rel) continue;
    entry.hits += 1;
    state.skipped.push(`${rel}${isDir ? '/' : ''} (${IGNORE_FILE}:${entry.lineno})`);
    return true;
  }
  return false;
}

function reportIgnores(state) {
  for (const line of [...state.skipped].sort(byCodepoint)) {
    process.stderr.write(`ignored: ${line}\n`);
  }
  for (const entry of state.entries) {
    if (entry.hits) continue;
    process.stderr.write(
      `unused-ignore: ${entry.target}${entry.isDir ? '/' : ''} (${IGNORE_FILE}:${entry.lineno})\n`);
  }
}

function declaredProfile(root) {
  for (const candidate of [join(root, 'docs', 'okf.yaml'), join(root, 'okf.yaml')]) {
    let text;
    try { text = readFileSync(candidate, 'utf8'); } catch { continue; }
    for (const line of text.split('\n')) {
      const m = PROFILE_RE.exec(line.replace(/\r$/, ''));
      if (m) return [candidate, m[1]];
    }
  }
  return [null, null];
}

function scalar(raw) {
  if (raw === undefined || raw === null) return '';
  return raw.trim();
}

function unquote(value) {
  const q = value[0];
  if ((q === '"' || q === "'") && value.length >= 2 && value.endsWith(q)) return value.slice(1, -1);
  return value;
}

function scalarViolation(key, value, lineno) {
  if (!value) return null;
  const q = value[0];
  if ((q === '"' || q === "'") && !(value.length >= 2 && value.endsWith(q))) {
    return `line ${lineno}: unterminated quoted value for '${key}'`;
  }
  if (value[0] === '[' && !value.endsWith(']')) {
    return `line ${lineno}: unterminated flow sequence for '${key}'`;
  }
  if (value[0] === '{' && !value.endsWith('}')) {
    return `line ${lineno}: unterminated flow mapping for '${key}'`;
  }
  return null;
}

function readBlockScalar(lines, start, style) {
  const body = [];
  let i = start;
  for (; i < lines.length; i += 1) {
    const line = lines[i].replace(/\r$/, '');
    if (!line.trim()) { body.push(''); continue; }
    if (line[0] !== ' ' && line[0] !== '\t') break;
    body.push(line.replace(/^[ \t]+/, ''));
  }
  while (body.length && !body[body.length - 1]) body.pop();
  if (style === '|') return [body.join('\n'), i];
  const folded = [];
  for (const line of body) {
    if (!line) { folded.push('\n'); continue; }
    if (folded.length && folded[folded.length - 1] !== '\n') folded.push(' ');
    folded.push(line);
  }
  return [folded.join(''), i];
}

function parseBlock(block) {
  const data = {};
  let seenKey = false;
  const lines = block.split('\n');
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i].replace(/\r$/, '');
    const lineno = i + 2;
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    if (line[0] === ' ' || line[0] === '\t') {
      if (!seenKey) return [null, `line ${lineno}: indented content before any key`];
      if (!NESTED_RE.test(line)) return [null, `line ${lineno}: unparseable nested content`];
      continue;
    }
    if (trimmed.startsWith('- ')) {
      return [null, `line ${lineno}: top-level sequence; frontmatter must be a mapping`];
    }
    const m = KEY_RE.exec(line);
    if (!m) return [null, `line ${lineno}: not a mapping entry`];
    const key = m[1];
    if (Object.prototype.hasOwnProperty.call(data, key)) {
      return [null, `line ${lineno}: duplicate key '${key}'`];
    }
    const value = scalar(m[2]);
    const sigil = BLOCK_RE.exec(value);
    if (sigil) {
      const [text, next] = readBlockScalar(lines, i + 1, sigil[1]);
      data[key] = text;
      seenKey = true;
      i = next - 1;
      continue;
    }
    const bad = scalarViolation(key, value, lineno);
    if (bad) return [null, bad];
    data[key] = unquote(value);
    seenKey = true;
  }
  return [data, null];
}

function readDoc(path) {
  let text;
  try { text = readFileSync(path, 'utf8'); } catch (err) { return [null, `unreadable: ${err.message}`]; }
  const lines = text.split('\n').map((l) => l.replace(/\r$/, ''));
  if (!lines.length || lines[0].trim() !== '---') return [null, 'no YAML frontmatter block'];
  for (let i = 1; i < lines.length; i += 1) {
    if (lines[i].trim() === '---') return parseBlock(lines.slice(1, i).join('\n'));
  }
  return [null, 'unterminated YAML frontmatter block'];
}

const isConcept = (name) => {
  const low = name.toLowerCase();
  return name.endsWith('.md') && !RESERVED.has(low) && !PROJECT_META.has(low);
};

function walk(root, ignores) {
  const out = [];
  const keep = (dirpath, name, isDir) =>
    !ignoreHit(ignores, relPath(root, join(dirpath, name)), isDir);
  const visit = (dirpath) => {
    let entries;
    try { entries = readdirSync(dirpath, { withFileTypes: true }); } catch { return; }
    const dirnames = entries
      .filter((e) => e.isDirectory() && !e.name.startsWith('.') && !SKIP_DIRS.has(e.name))
      .filter((e) => keep(dirpath, e.name, true))
      .map((e) => e.name).sort(byCodepoint);
    const filenames = entries
      .filter((e) => e.isFile())
      .filter((e) => keep(dirpath, e.name, false))
      .map((e) => e.name).sort(byCodepoint);
    out.push([dirpath, dirnames, filenames]);
    for (const d of dirnames) visit(join(dirpath, d));
  };
  visit(root);
  return out;
}

function indexable(root, ignores) {
  const tree = walk(root, ignores);
  const carries = new Map();
  for (let i = tree.length - 1; i >= 0; i -= 1) {
    const [dirpath, dirnames, filenames] = tree[i];
    const own = filenames.some(isConcept);
    const below = dirnames.some((d) => carries.get(join(dirpath, d)));
    carries.set(dirpath, own || below);
  }
  const ordered = [...tree].reverse().filter(([d]) => carries.get(d));
  return [ordered, carries];
}

function priorDescriptions(dirpath) {
  const found = new Map();
  let lines;
  try { lines = readFileSync(join(dirpath, 'index.md'), 'utf8').split('\n'); } catch { return found; }
  let inSubdirs = false;
  for (const line of lines) {
    if (line.startsWith('# ')) { inSubdirs = line.slice(2).trim() === SUBDIR_HEADING; continue; }
    if (!inSubdirs) continue;
    const m = ENTRY_RE.exec(line);
    if (m && m[3]) found.set(join(dirpath, m[1]), m[3].trim());
  }
  return found;
}

function renderRows(heading, rows) {
  const out = [`# ${heading}`, ''];
  const sorted = [...rows].sort((a, b) => byCodepoint(a[0].toLowerCase(), b[0].toLowerCase()));
  for (const [title, link, desc] of sorted) {
    out.push(`* [${title}](${link})${desc ? ` - ${desc}` : ''}`);
  }
  return out.join('\n');
}

function render(sections, subdirs, isRoot) {
  const blocks = [];
  for (const heading of [...sections.keys()].sort(byCodepoint)) {
    blocks.push(renderRows(heading, sections.get(heading)));
  }
  if (subdirs.length) blocks.push(renderRows(SUBDIR_HEADING, subdirs));
  const body = `${GEN_MARKER}\n\n${blocks.join('\n\n')}\n`;
  return isRoot ? `---\nokf_version: "${OKF_VERSION}"\n---\n\n${body}` : body;
}

function cmdIndex(root, toStdout, described, ignores) {
  const [dirs, carries] = indexable(root, ignores);
  if (!dirs.length) {
    process.stderr.write(`okf.mjs: no concept documents found under ${root} - nothing written\n`);
    reportIgnores(ignores);
    return 77;
  }

  const relOf = (p) => relPath(root, p);
  const overlong = [];

  const resolved = new Map();
  for (const [dirpath] of dirs) {
    for (const [k, v] of priorDescriptions(dirpath)) resolved.set(k, oneLine(v));
  }
  for (const [k, v] of described) {
    const text = gated(v, relOf(k) || '.', overlong);
    if (text) resolved.set(k, text);
    else resolved.delete(k);
  }

  const pending = new Set();
  let written = 0;

  for (const [dirpath, dirnames, filenames] of dirs) {
    const sections = new Map();
    for (const name of filenames) {
      if (!isConcept(name)) continue;
      const [fm] = readDoc(join(dirpath, name));
      const front = fm || {};
      const heading = String(front.type || '').trim() || UNTYPED_HEADING;
      const title = String(front.title || '').trim() || name.slice(0, -3);
      const desc = gated(front.description, relOf(join(dirpath, name)), overlong);
      if (!sections.has(heading)) sections.set(heading, []);
      sections.get(heading).push([title, name, desc]);
    }

    const subdirs = [];
    for (const name of dirnames) {
      const child = join(dirpath, name);
      if (!carries.get(child)) continue;
      subdirs.push([name, `${name}/index.md`, resolved.get(child) || '']);
    }

    if (!sections.size && !subdirs.length) continue;

    if (dirpath !== root && !resolved.get(dirpath)) {
      const entries = [...sections.values()].flat();
      if (entries.length === 1 && entries[0][2] && !subdirs.length) {
        resolved.set(dirpath, entries[0][2]);
      } else {
        pending.add(relative(root, dirpath).split(sep).join('/'));
      }
    }

    const text = render(sections, subdirs, dirpath === root);
    const target = join(dirpath, 'index.md');
    if (toStdout) {
      process.stdout.write(`==> ${relative(root, target).split(sep).join('/')} <==\n${text}\n`);
    } else {
      writeFileSync(target, text, 'utf8');
      written += 1;
    }
  }

  if (!toStdout) process.stderr.write(`okf.mjs: wrote ${written} index file(s)\n`);
  reportIgnores(ignores);
  for (const rel of [...pending].sort(byCodepoint)) {
    process.stderr.write(`needs-description: ${rel}\n`);
  }
  for (const report of [...overlong].sort(byCodepoint)) {
    process.stderr.write(`long-description: ${report}\n`);
  }
  return 0;
}

function cmdCheck(root, ignores) {
  const violations = [];
  const notes = [];
  let scanned = 0;
  const rootIndex = join(root, 'index.md');

  for (const [dirpath, , filenames] of walk(root, ignores)) {
    for (const name of filenames) {
      if (!name.endsWith('.md')) continue;
      const path = join(dirpath, name);
      const rel = relPath(root, path);
      const low = name.toLowerCase();
      if (low === 'log.md') {
        notes.push(`${rel}: log.md duplicates git history (this skill removes it; not a §11 failure)`);
        continue;
      }
      if (low === 'index.md') {
        if (path !== rootIndex) {
          const first = readFileSync(path, 'utf8').split('\n')[0].trim();
          if (first === '---') {
            violations.push(`${rel}: index.md carries frontmatter; only the bundle-root index may (§8, §12)`);
          }
        }
        continue;
      }
      if (PROJECT_META.has(low)) continue;
      scanned += 1;
      const [fm, err] = readDoc(path);
      if (err) { violations.push(`${rel}: ${err}`); continue; }
      if (!String(fm.type || '').trim()) {
        violations.push(`${rel}: missing or empty required key 'type' (§4.1, §11)`);
      }
      const desc = oneLine(fm.description);
      if (desc.length > DESC_MAX) {
        notes.push(`${rel}: description is ${desc.length} chars (max ${DESC_MAX}); the index omits it rather than truncating (§4.1 is one sentence)`);
      }
    }
  }

  for (const note of notes) process.stdout.write(`note: ${note}\n`);
  reportIgnores(ignores);

  if (scanned === 0) {
    process.stderr.write(`okf.mjs: evaluated 0 concept documents under ${root} - nothing was verified\n`);
    return 77;
  }

  for (const line of violations) process.stdout.write(`${line}\n`);
  process.stdout.write(`okf.mjs: ${scanned} document(s) evaluated, ${violations.length} violation(s)\n`);
  return violations.length ? 1 : 0;
}

function cmdWire(root, toStdout) {
  if (!existsSync(join(root, 'index.md'))) {
    process.stderr.write(`okf.mjs: no index.md at ${root} - run \`index\` first\n`);
    return 1;
  }

  const touched = [];
  for (const name of PROSE_ENTRY_FILES) {
    const path = join(root, name);
    let text = '';
    try { text = readFileSync(path, 'utf8'); } catch { text = ''; }
    let updated;
    let action;
    if (ENTRY_BLOCK_RE.test(text)) {
      updated = text.replace(ENTRY_BLOCK_RE, () => ENTRY_BLOCK);
      action = 'updated';
    } else {
      updated = (text.trim() ? `${text.replace(/\n+$/, '')}\n\n` : '') + ENTRY_BLOCK + '\n';
      action = 'added';
    }
    if (updated === text) action = 'unchanged';
    if (toStdout) process.stdout.write(`==> ${name} (${action}) <==\n${ENTRY_BLOCK}\n`);
    else if (action !== 'unchanged') writeFileSync(path, updated, 'utf8');
    touched.push(`${name} ${action}`);
  }

  const geminiPath = join(root, IMPORT_ENTRY_FILE);
  if (existsSync(geminiPath)) {
    const text = readFileSync(geminiPath, 'utf8');
    if (text.split(/\s+/).includes(IMPORT_LINE)) {
      touched.push(`${IMPORT_ENTRY_FILE} unchanged`);
    } else {
      if (!toStdout) writeFileSync(geminiPath, `${text.replace(/\n+$/, '')}\n${IMPORT_LINE}\n`, 'utf8');
      touched.push(`${IMPORT_ENTRY_FILE} added`);
    }
  }

  process.stderr.write(`okf.mjs: ${touched.join(', ')}\n`);
  return 0;
}

function usage(message) {
  if (message) process.stderr.write(`okf.mjs: ${message}\n`);
  process.stderr.write(`${USAGE}\n`);
  return 64;
}

function main(argv) {
  if (argv.includes('--version')) {
    process.stdout.write(`okf.mjs ${VERSION} (OKF v${OKF_VERSION})\n`);
    return 0;
  }
  if (!argv.length) return usage('no command given');

  const [command, ...rest] = argv;
  if (!['index', 'check', 'wire'].includes(command)) return usage(`unknown command '${command}'`);

  let toStdout = false;
  const described = new Map();
  const positional = [];
  for (let i = 0; i < rest.length; i += 1) {
    const arg = rest[i];
    if (arg === '--stdout') toStdout = true;
    else if (arg === '--describe') {
      i += 1;
      if (i >= rest.length) return usage('--describe needs <dir>=<text>');
      if (!rest[i].includes('=')) return usage(`--describe expects <dir>=<text>, got '${rest[i]}'`);
      const at = rest[i].indexOf('=');
      described.set(resolve(rest[i].slice(0, at)), rest[i].slice(at + 1).trim());
    } else if (arg.startsWith('--')) return usage(`unknown option '${arg}'`);
    else positional.push(arg);
  }

  if (positional.length !== 1) return usage(`expected exactly one <bundle-root>, got ${positional.length}`);
  const root = resolve(positional[0]);
  try { if (!statSync(root).isDirectory()) throw new Error('not a dir'); }
  catch { return usage(`not a directory: ${positional[0]}`); }

  const [manifest, profile] = declaredProfile(root);
  if (profile) {
    process.stderr.write(
      `okf.mjs: ${relPath(root, manifest)} declares profile ${profile} - out of scope, nothing written\n`);
    process.stderr.write(
      `okf.mjs: that profile ships its own generator, and a repo enforcing byte-exact index sync at commit would reject v${OKF_VERSION} output, denying every later commit\n`);
    return 3;
  }

  if (command === 'wire') {
    if (described.size) return usage('wire does not take --describe');
    return cmdWire(root, toStdout);
  }

  const ignores = readIgnores(root);
  if (command === 'check') {
    if (toStdout || described.size) return usage('check takes no options');
    return cmdCheck(root, ignores);
  }
  return cmdIndex(root, toStdout, described, ignores);
}

process.exit(main(process.argv.slice(2)));
